require("config.lazy")
require("config.mappings")
require("config.general")
require("config.colors")
require("config.autocmds")
require("custom.format")
require("custom.statusline")
require("custom.finder")
